apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrapers-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scrapers
  template:
    metadata:
      labels:
        app: scrapers
    spec:
      containers:
        - name: scrapers
          image: stefanruvceski/scrapers
          env:
            - name: MONGO_URI
              value: 'mongodb://scrapers-mongo-srv:27017/scrapers'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                    fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: scraping 
---
apiVersion: v1
kind: Service
metadata:
  name: scrapers-srv
spec:
  selector:
    app: scrapers
  ports:
    - name: scrapers
      protocol: TCP
      port: 3000
      targetPort: 3000
